[#41] Feat: 소셜 로그인 기능 구현
AK-47-GrandMother/WakuWaku-BackEnd pull request #43
Opened 2024-05-13 22:14 UTC by min2h

## PR Checklist

- [ ] Commit Convention
- [ ] 변경 사항에 대한 테스트
- [ ] 문서 추가/업데이트

## PR Type

- [ ] 버그 수정
- [ ] 기능 추가
- [ ] 코드 스타일 변경
- [ ] 리팩토링
- [ ] 빌드 관련
- [ ] CI 관련
- [ ] 문서 내용 변경
- [ ] 기타... 설명:

## Issue 번호
ex)
Issue Number: #123

### 아래에 작성
Issue Number:

## 작업 내용(기대 효과)
- 크리티컬한 부분은 남김(코드 첨가)
- 클래스 단위로 어떤 기능 구현했는지만

ex)
'MemberService.class' - 'getAll()'

어쩌구 해서 어쩌구 하는 메소드

'MemberRequestDto.class'

뭘 하기 위해서 필요한 Dto

### 아래에 작성

멤버 소셜 로그인 구현 및 멤버 관련 API 수정

## 기타 사항

2024-06-24 11:18 UTC, jjunsik requested changes

2024-06-24 11:18 UTC, jjunsik commented on src/test/java/dev/backend/wakuwaku/domain/member/service/MemberServiceTest.java
> +                .isInstanceOf(RuntimeException.class)
예외 테스트 코드 수정해주세요!

2024-06-24 11:18 UTC, jjunsik commented on src/test/java/dev/backend/wakuwaku/domain/member/service/MemberServiceTest.java
> +                .isInstanceOf(RuntimeException.class)
여기도요!

2024-06-24 11:18 UTC, jjunsik commented on src/test/java/dev/backend/wakuwaku/domain/oauth/service/OauthServiceTest.java
> +                .isInstanceOf(RuntimeException.class)
여기도요!!

2024-06-24 11:18 UTC, jjunsik commented on src/test/java/dev/backend/wakuwaku/global/infra/oauth/google/client/GoogleApiClientImplTest.java
> +        ResponseEntity<GoogleMemberResponse> responseEntity = new ResponseEntity<>(new GoogleMemberResponse("123", "test@example.com", "John", "Doe", "https://example.com/pic.jpg"), HttpStatus.OK);
BaseEntity로 수정되어야 하나요?? 몰라서...

2024-06-24 11:18 UTC, jjunsik commented on src/test/java/dev/backend/wakuwaku/global/infra/oauth/oauthcode/OauthCodeRequestUrlProviderCompositeTest.java
> +public class OauthCodeRequestUrlProviderCompositeTest {
네이버, 카카오에 대한 테스트 코드는 작성하지 않아도 되나요? 이것 또한 몰라서...

2024-06-24 14:24 UTC, min2h commented on src/main/java/dev/backend/wakuwaku/domain/member/dto/request/MemberUpdateRequest.java
> +    public void setMemberPassword(String nickname) {
엇 ! 이부분도 Oauth 소셜로그인 기능 추가하면서 삭제했습니다~!

2024-06-24 14:24 UTC, min2h commented on src/main/java/dev/backend/wakuwaku/domain/member/controller/MemberController.java
> +                .collect(toList()));
Oauth 소셜로그인 기능 추가하면서 삭제된 부분입니다!

2024-06-24 14:30 UTC, min2h commented on src/main/java/dev/backend/wakuwaku/domain/member/service/MemberService.java
> +                    throw new RuntimeException(ExceptionStatus.DUPLICATED_EMAIL.getMessage());
네 수정했습니다~

```
private void validateDuplicateMember(Member member) {
        memberRepository.findByEmail
                        (member.getEmail())
                .ifPresent(m -> {
                    throw DUPLICATED_EMAIL;
                });
    }
```

2024-06-24 14:32 UTC, min2h commented on src/main/java/dev/backend/wakuwaku/domain/member/service/MemberService.java
> +                        () ->  new RuntimeException(ExceptionStatus.NONE_USER.getMessage())
```
public Member findById(Long id) {
        return memberRepository.findById(id)
                .orElseThrow(
                        () ->  NONE_USER
                );
    }

    /*
    회원 정보 수정
     */
    public Long update(Long id, MemberUpdateRequest memberUpdateRequest) {
        Member member = memberRepository.findById(id)
                .orElseThrow(
                        () ->  NONE_USER
                );

        member.setNickname(memberUpdateRequest.getNickname());
        member.setProfileImageUrl(memberUpdateRequest.getProfileImageUrl());
        member.setBirthday(memberUpdateRequest.getBirthday());

        memberRepository.save(member);

        return member.getId();
    }
```

수정했습니다

2024-06-24 14:35 UTC, min2h commented on src/test/java/dev/backend/wakuwaku/domain/member/service/MemberServiceTest.java
> +                .isInstanceOf(RuntimeException.class)
```
    @Test
    @DisplayName("존재하지 않는 ID로 회원 정보 수정할 때 예외 발생")
    void updateNonExistingId() {
        // given
        given(memberRepository.findById(anyLong())).willReturn(Optional.empty());
        MemberUpdateRequest updateRequest = new MemberUpdateRequest("newNickname", "newProfileUrl", "1991-01-01");

        // when, then
        assertThatThrownBy(() -> memberService.findById(1L))
                .isInstanceOf(WakuWakuException.class)
                .isEqualTo(NONE_USER);
        then(memberRepository).should().findById(anyLong());
        then(memberRepository).should(never()).save(any());
    }

```
수정했습니다!

2024-06-24 14:36 UTC, min2h commented on src/test/java/dev/backend/wakuwaku/domain/member/service/MemberServiceTest.java
> +                .isInstanceOf(RuntimeException.class)
```
@Test
    @DisplayName("존재하지 않는 ID로 회원 조회할 때 예외 발생")
    void findByIdNonExistingId() {
        // given
        given(memberRepository.findById(anyLong())).willReturn(Optional.empty());

        // when, then
        assertThatThrownBy(() -> memberService.findById(1L))
                .isInstanceOf(WakuWakuException.class)
                .isEqualTo(NONE_USER);
    }

```

수정했습ㄴㅣ다 👍

2024-06-24 14:37 UTC, min2h commented on src/test/java/dev/backend/wakuwaku/domain/oauth/service/OauthServiceTest.java
> +                .isInstanceOf(RuntimeException.class)
```
@Test
    @DisplayName("로그인 실패 시 예외 발생")
    void loginFailure() {
        // Given
        OauthServerType oauthServerType = OauthServerType.KAKAO;

        given(oauthMemberClientComposite.fetch(eq(oauthServerType), eq(AUTH_CODE))).willThrow(new RuntimeException("OAuth client error"));

        // When / Then
        assertThatThrownBy(() -> oauthService.login(oauthServerType, AUTH_CODE))
                .isInstanceOf(WakuWakuException.class)
                .isEqualTo(FALIED_TO_LOGIN);
    }
```

2024-06-24 14:39 UTC, min2h commented on src/test/java/dev/backend/wakuwaku/global/infra/oauth/google/client/GoogleApiClientImplTest.java
> +        ResponseEntity<GoogleMemberResponse> responseEntity = new ResponseEntity<>(new GoogleMemberResponse("123", "test@example.com", "John", "Doe", "https://example.com/pic.jpg"), HttpStatus.OK);
이 부분은 이해하지 못 했어요.  어떤 부분인가요?

2024-06-25 14:50 UTC, min2h commented on src/main/java/dev/backend/wakuwaku/domain/member/service/MemberService.java
> +        member.setBirthday(memberUpdateRequest.getBirthday());
```
/*
    회원 정보 수정
     */
    public Long update(Long id, MemberUpdateRequest memberUpdateRequest) {
        Member member = memberRepository.findById(id)
                .orElseThrow(
                        () -> NONE_USER
                );

        member.updateNickname(memberUpdateRequest.getNickname());
        member.updateProfileImageUrl(memberUpdateRequest.getProfileImageUrl());
        member.updateBirthday(memberUpdateRequest.getBirthday());

        memberRepository.save(member);

        return member.getId();
    }
```

수정했습니다~~

2024-06-25 14:56 UTC, min2h commented on src/main/java/dev/backend/wakuwaku/domain/oauth/service/OauthService.java
> +                member.setRole(Role.USER);
```
member = Member.builder()
                        .oauthServerId(oauthMember.getOauthId().getOauthServerId())
                        .oauthServerType(oauthMember.getOauthId().getOauthServerType())
                        .email(oauthMember.getEmail())
                        .birthday(oauthMember.getBirthday())
                        .nickname(oauthMember.getNickname())
                        .profileImageUrl(oauthMember.getProfileImageUrl())
                        .role(Role.USER)
                        .build();
```

수정했어요~

2024-06-25 14:56 UTC, min2h commented on src/main/java/dev/backend/wakuwaku/domain/oauth/service/OauthService.java
> +            throw new RuntimeException(ExceptionStatus.FALIED_TO_LOGIN.getMessage(), e);
```
catch (Exception e) {
            log.error("로그인 중 오류 발생: {}", e.getMessage(), e);
            throw WakuWakuException.FAILED_TO_LOGIN;
        }

```
수정했습니다!

2024-06-25 14:59 UTC, min2h commented on src/main/java/dev/backend/wakuwaku/global/config/WebConfig.java
> +public class WebConfig implements WebMvcConfigurer {
이 부분은 지금 필요없는 부분 같아요. 소셜 로그인 구현 초기에 Spring Security를 사용하기 위해 추가했었습니다.

2024-06-25 14:59 UTC, min2h commented on src/main/java/dev/backend/wakuwaku/global/exception/ExceptionStatus.java
> +    // oauth exception
네엡 수정했습니다~

2024-06-25 15:00 UTC, min2h commented on src/main/java/dev/backend/wakuwaku/global/exception/ExceptionStatus.java
> +    // oauth exception
```
// common exception
    INVALID_PARAMETER(BAD_REQUEST, 2000, "잘못된 요청이 존재합니다."),
    INVALID_URL(BAD_REQUEST, 2001, "잘못된 URL 요청입니다."),
    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, 2002,"서버 내부 오류입니다."),
    NOT_EXISTED_FILE(NOT_EXTENDED, 2003,"존재하지 않는 파일입니다."),

    // member exception
    DUPLICATED_EMAIL(CONFLICT, 3000, "중복된 이메일이 존재합니다."),
    NONE_USER(NOT_FOUND, 3001, "존재하지 않는 회원입니다."),
    DEACTIVATED_USER(NOT_FOUND ,3002, "이미 탈퇴한 사용자입니다."),


    // google places exception
    INVALID_SEARCH_WORD(BAD_REQUEST, 4000, "검색어를 입력하지 않았습니다."),
    NOT_EXISTED_NEXT_PAGE_TOKEN(BAD_REQUEST, 4001, "NEXT PAGE TOKEN 이 존재하지 않습니다."),
    NONE_PHOTO_URL(NOT_FOUND, 4002, "PHOTO URL이 존재하지 않습니다."),
    NOT_EXISTED_PLACE_ID(BAD_REQUEST, 4003, "PLACE ID 가 존재하지 않습니다."),
    NOT_EXISTED_DETAILS_RESPONSE(BAD_REQUEST, 4004, "Details Response 가 존재하지 않습니다."),



    // oauth exception
    FALIED_TO_LOGIN(NOT_FOUND ,5000, "로그인 중 오류가 발생했습니다. 다시 시도해 주세요."),
    NOT_EXISTED_SOCIAL_TYPE(NOT_FOUND ,5001, "지원하지 않는 소셜 타입입니다."),
    NOT_EXISTED_MEMBER_INFO(NOT_FOUND ,5002, "사용자 정보를 찾을 수 없습니다.");
```

2024-06-25 15:03 UTC, min2h commented on src/main/java/dev/backend/wakuwaku/global/infra/oauth/oauthcode/OauthCodeRequestUrlProviderComposite.java
> +                .orElseThrow(() -> new RuntimeException(ExceptionStatus.NOT_EXISTED_SOCIAL_TYPE.getMessage()));
수정했씁니다~!~!

2024-06-25 15:08 UTC, min2h commented on src/test/java/dev/backend/wakuwaku/domain/member/service/MemberServiceTest.java
> +        member.setId(1L);
수정했습니다!

2024-06-26 07:14 UTC, jjunsik requested changes

2024-06-26 07:14 UTC, jjunsik commented on src/main/java/dev/backend/wakuwaku/domain/oauth/service/OauthService.java
> +                    memberRepository.save(member);
JPA에서 관리하는 Entity를 수정하면 더티체킹에 의해 save 메서드를 호출하지 않아도 해당 메서드가 끝나는 시점에 update 쿼리가 날라갑니다!
따라서 save 호출이  불필요하다면 삭제해주세요!

2024-06-26 07:14 UTC, jjunsik commented on src/test/java/dev/backend/wakuwaku/domain/member/service/MemberServiceTest.java
> +        member.setCheckStatus("Y");
setter 수정은 아직인건가요!

2024-06-26 07:14 UTC, jjunsik commented on src/test/java/dev/backend/wakuwaku/domain/member/service/MemberServiceTest.java
> +        existingMember.setCheckStatus("Y"); // "Y"로 설정하여 중복 상황을 시뮬레이트
setter 수정 해주세요!

2024-06-26 07:14 UTC, jjunsik commented on src/test/java/dev/backend/wakuwaku/domain/member/service/MemberServiceTest.java
> +        newMember.setCheckStatus("N"); // "N"으로 설정하여 중복 상황을 회피
여기도요!

2024-06-27 13:26 UTC, min2h commented on src/main/java/dev/backend/wakuwaku/domain/oauth/service/OauthService.java
```
public Map<String, Long> login(OauthServerType oauthServerType, String authCode) throws WakuWakuException {
        OauthMember oauthMember;
        try {
            oauthMember = oauthMemberClientComposite.fetch(oauthServerType, authCode);
        } catch (Exception e) {
            log.error("OAuth 멤버 정보 가져오기 중 오류 발생: {}", e.getMessage(), e);
            throw WakuWakuException.FAILED_TO_LOGIN;
        }

        Optional<Member> optionalMember;
        try {
            optionalMember = memberRepository.findByEmail(oauthMember.getEmail());
        } catch (Exception e) {
            log.error("회원 정보 조회 중 오류 발생: {}", e.getMessage(), e);
            throw WakuWakuException.FAILED_TO_LOGIN;
        }

        Member member;
        if (optionalMember.isPresent()) {
            member = optionalMember.get();
            if (member.getCheckStatus().equals("N")) {
                member.setCheckStatus("Y");
                try {
                    memberRepository.save(member);
                } catch (Exception e) {
                    log.error("회원 정보 업데이트 중 오류 발생: {}", e.getMessage(), e);
                    throw WakuWakuException.FAILED_TO_LOGIN;
                }
            }
        } else {
            member = Member.builder()
                    .oauthServerId(oauthMember.getOauthId().getOauthServerId())
                    .oauthServerType(oauthMember.getOauthId().getOauthServerType())
                    .email(oauthMember.getEmail())
                    .birthday(oauthMember.getBirthday())
                    .nickname(oauthMember.getNickname())
                    .profileImageUrl(oauthMember.getProfileImageUrl())
                    .role(Role.USER)
                    .build();
            try {
                memberRepository.save(member);
            } catch (Exception e) {
                log.error("새로운 회원 저장 중 오류 발생: {}", e.getMessage(), e);
                throw WakuWakuException.FAILED_TO_LOGIN;
            }
        }

        Map<String, Long> response = new HashMap<>();
        response.put("id", member.getId());
        return response;
    }
```

2024-06-27 13:27 UTC, min2h commented on src/main/java/dev/backend/wakuwaku/domain/oauth/service/OauthService.java
> +    public Map<String, Long> login(OauthServerType oauthServerType, String authCode) throws WakuWakuException {
위에 수정된 코드 올렸습니다~

2024-06-27 13:43 UTC, min2h commented on src/test/java/dev/backend/wakuwaku/domain/member/service/MemberServiceTest.java
> +        member.setCheckStatus("Y");
```
        String email = "test@example.com";
        Member newMember = new Member();
        newMember.createEmail(email);
```

2024-06-27 13:46 UTC, min2h commented on src/test/java/dev/backend/wakuwaku/domain/member/service/MemberServiceTest.java
> +        existingMember.setCheckStatus("Y"); // "Y"로 설정하여 중복 상황을 시뮬레이트
```
void deactivateById() {
        // given
        Long memberId = 1L;
        Member member = new Member();
        member.createId(memberId);
        member.createCheckstatus("Y");

        given(memberRepository.findById(memberId)).willReturn(Optional.of(member));

        // when
        memberService.deactivateById(memberId);

        // then
        then(memberRepository).should().findById(memberId);
        assertThat(member.getCheckStatus()).isEqualTo("N");
        then(memberRepository).should().save(member);
    }
```

2024-06-27 13:48 UTC, min2h commented on src/test/java/dev/backend/wakuwaku/domain/member/service/MemberServiceTest.java
> +        existingMember.setCheckStatus("Y"); // "Y"로 설정하여 중복 상황을 시뮬레이트
```
void loginSuccess() {
        // Given
        OauthServerType oauthServerType = OauthServerType.KAKAO;
        OauthId oauthId = new OauthId("test_oauth_server_id", oauthServerType);
        OauthMember oauthMember = new OauthMember(oauthId, NICKNAME, PROFILE_IMAGE_URL, EMAIL, BIRTHDAY);
        Member existingMember = new Member();
        existingMember.createEmail(EMAIL);
        existingMember.createNickname(NICKNAME);
        existingMember.createProfileImageUrl(PROFILE_IMAGE_URL);
        existingMember.createtBirthday(BIRTHDAY);
```

2024-06-27 13:49 UTC, min2h commented on src/test/java/dev/backend/wakuwaku/domain/member/service/MemberServiceTest.java
> +        newMember.setCheckStatus("N"); // "N"으로 설정하여 중복 상황을 회피
```
void loginSuccess() {
        // Given
        OauthServerType oauthServerType = OauthServerType.KAKAO;
        OauthId oauthId = new OauthId("test_oauth_server_id", oauthServerType);
        OauthMember oauthMember = new OauthMember(oauthId, NICKNAME, PROFILE_IMAGE_URL, EMAIL, BIRTHDAY);
        Member existingMember = new Member();
        existingMember.createEmail(EMAIL);
        existingMember.createNickname(NICKNAME);
        existingMember.createProfileImageUrl(PROFILE_IMAGE_URL);
        existingMember.createtBirthday(BIRTHDAY);
```

2024-06-27 18:25 UTC, jjunsik requested changes

2024-06-27 18:25 UTC, jjunsik commented on src/main/java/dev/backend/wakuwaku/domain/oauth/service/OauthService.java
> +        }
한 곳에서만 터지는 줄 알고 발생하는 부분에만 try로 묶어달라고 한 건데 연속적인 코드에서 같은 예외가 발생하면 하나로 합쳐도 되지 않을까요?
괜히 번거롭게 했네요 ㅠㅠ

2024-06-27 18:25 UTC, jjunsik commented on src/main/java/dev/backend/wakuwaku/domain/oauth/service/OauthService.java
> +            member.setCheckStatus("Y");
createCheckStatus 로 변경한 것을 보았는데 있길래 의아했습니다.
알고보니 Member 클래스에 @Setter 가 있더군요! 다른 클래스에도 해당 애노테이션이 붙어 있다면 삭제해주세요!!
해당 코드는 변경 부탁드립니다!!

2024-06-29 13:34 UTC, min2h commented on src/main/java/dev/backend/wakuwaku/domain/oauth/service/OauthService.java
> +        }
원복해써용 ㅎㅎ

2024-06-29 13:44 UTC, min2h commented on src/main/java/dev/backend/wakuwaku/domain/oauth/service/OauthService.java
> +            member.setCheckStatus("Y");
네

2024-06-30 09:21 UTC, jjunsik commented on src/main/java/dev/backend/wakuwaku/domain/oauth/service/OauthService.java
> +                    memberRepository.save(member);
이 부분 깜빡하신 것 같은데 확인 후 수정이 필요하다면 수정해주세요!

2024-06-30 09:22 UTC, jjunsik requested changes

2024-06-30 09:22 UTC, jjunsik commented on src/main/java/dev/backend/wakuwaku/domain/oauth/service/OauthService.java
> +                    member.setCheckStatus("Y");
이게 왜 또 여기에 나타난 것인지....

2024-06-30 09:22 UTC, jjunsik requested changes

2024-06-30 09:22 UTC, jjunsik commented on src/main/java/dev/backend/wakuwaku/domain/oauth/service/OauthService.java
> +                    memberRepository.save(member);
이 부분 깜빡하신 것 같은데 확인 후 수정이 필요하다면 수정해주세요!

2024-06-30 11:21 UTC, min2h commented on src/main/java/dev/backend/wakuwaku/domain/oauth/service/OauthService.java
> +                    member.setCheckStatus("Y");
```
 public Map<String, Long> login(OauthServerType oauthServerType, String authCode) {
        try {
            OauthMember oauthMember = oauthMemberClientComposite.fetch(oauthServerType, authCode);

            Optional<Member> optionalMember = memberRepository.findByEmail(oauthMember.getEmail());

            Member member;
            if (optionalMember.isPresent()) {
                member = optionalMember.get();
                if (member.getCheckStatus().equals("N")) {
                    member.updateCheckstatus("Y");
                }
            } else {
                // 새로운 회원 생성
                member = Member.builder()
                        .oauthServerId(oauthMember.getOauthId().getOauthServerId())
                        .oauthServerType(oauthMember.getOauthId().getOauthServerType())
                        .email(oauthMember.getEmail())
                        .birthday(oauthMember.getBirthday())
                        .nickname(oauthMember.getNickname())
                        .profileImageUrl(oauthMember.getProfileImageUrl())
                        .role(Role.USER)
                        .build();
            }

            memberRepository.save(member);
            Map<String, Long> response = new HashMap<>();
            response.put("id", member.getId());
            return response;

        } catch (Exception e) {
            log.error("로그인 중 오류 발생: {}", e.getMessage(), e);
            throw WakuWakuException.FAILED_TO_LOGIN;
        }
    }
```

아래 코드리뷰 내용과 일치하는 메서드라 수정 후 올립니다!

2024-07-03 14:51 UTC, min2h commented on src/main/java/dev/backend/wakuwaku/domain/oauth/service/OauthService.java
> +                    memberRepository.save(member);
마지막으로 이 부분 수정 커밋했습니다~!

2024-07-08 13:48 UTC, jjunsik approved these changes
**정말 고생 많으셨습니다!!!!!**

2024-07-08 15:47 UTC, merged